export const messengerAbi = [
  {
    type: 'function',
    name: 'deposit',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'bytes32', name: 'to' },
      { type: 'address', name: 'token' },
      { type: 'uint256', name: 'value' },
      { type: 'bool', name: 'recipientIsContract' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'depositETH',
    stateMutability: 'payable',
    inputs: [
      { type: 'bytes32', name: 'to' },
      { type: 'bool', name: 'recipientIsContract' },
    ],
    outputs: [{ type: 'bool', name: 'success' }],
  },
  {
    type: 'function',
    name: 'depositWithPermit',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'bytes32', name: 'to' },
      { type: 'address', name: 'token' },
      { type: 'uint256', name: 'value' },
      { type: 'uint256', name: 'deadline' },
      { type: 'uint8', name: 'v' },
      { type: 'bytes32', name: 'r' },
      { type: 'bytes32', name: 's' },
      { type: 'bool', name: 'recipientIsContract' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'paused',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool', name: '' }],
  },
  {
    type: 'function',
    name: 'depositCap',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'token' }],
    outputs: [{ type: 'uint256', name: '' }],
  },
  {
    type: 'function',
    name: 'totalDeposits',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'token' }],
    outputs: [{ type: 'uint256', name: '' }],
  },
  {
    type: 'function',
    name: 'whitelistedTokens',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'token' }],
    outputs: [{ type: 'bool', name: 'isValid' }],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'Deposit',
    inputs: [
      { type: 'bytes32', name: 'recipient', indexed: true },
      { type: 'uint64', name: 'nonce', indexed: true },
      { type: 'bytes32', name: 'depositHash', indexed: true },
      { type: 'address', name: 'token', indexed: false },
      { type: 'uint64', name: 'value', indexed: false },
      { type: 'bool', name: 'recipientIsContract', indexed: false },
    ],
  },
  {
    type: 'error',
    name: 'EnforcedPause',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InsufficientAmountError',
    inputs: [],
  },
  {
    type: 'error',
    name: 'TokenNotWhitelistedError',
    inputs: [{ type: 'address', name: '' }],
  },
  {
    type: 'error',
    name: 'DepositCapExceededError',
    inputs: [],
  },
] as const
